n = str(input('Digite seu nome completo: '))
nome = n.split()
print('Prazer em conhecê-lo"')
print('O seu primeiro nome é {}'.format(nome[0]))
print('O seu último nome é {}'.format(nome[len(nome)-1]))